application: kaist-wst660-bmaingret
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
#Endpoints handler
- url: /_ah/spi/.*
  script: services_api.application
#Generic handler
- url: /.*
  script: helloworld.app
